package edu.carroll.doin_backend.web.dto;

/**
 * This record class is used to transport the JWT-Token between the backend and frontend, specifically after successfully logging in.
 * <BR>
 * A record class comes with autogenerated getters and constructors.
 *
 */
public class TokenDTO {

    private final String token;

    public TokenDTO(String token) {
        this.token = token;
    }

    public TokenDTO() {
        this.token = null;
    }

    public String getToken() {
        return token;
    }

}
