package edu.carroll.doin_backend.web.dto;

/**
 * This record class is used to transport the JWT-Token between the backend and frontend, specifically after successfully logging in.
 * <BR>
 * A record class comes with autogenerated getters and constructors.
 *
 */
public record TokenDTO(String token) {

}
