package edu.carroll.doin_backend.web.repository;

import edu.carroll.doin_backend.web.model.SecurityQuestion;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface SecurityQuestionRepository extends JpaRepository<SecurityQuestion, Integer> {
    /**
     * Finds a list of security questions by their id.
     * <p>
     * This method is autogenerated by Spring, but it will find all SecurityQuestions with the id that matches the id parameter. The id is the primary key, so the returned list will be at most length = 1.
     * </p>
     *
     * @param id the id to search for
     * @return a list of {@link SecurityQuestion} objects that have matching id's with the id parameter.
     */
    List<SecurityQuestion> findbyId(Integer id);
}
