import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ApiService } from '../services/api.service';
import { Router } from '@angular/router';

// TokenDTO interface for TypeScript
export interface TokenDTO {
  token: string;
}

@Component({
  selector: 'app-login',
  standalone: true,
  imports:[FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  loginData = {
    username: '',
    password: ''
  };

  constructor(private router: Router, private apiService : ApiService) { }

  ngOnInit(): void {
    const token = sessionStorage.getItem('jwtToken');
    if (token) {
      // showing for now it has it
      console.log("has Jwt Token");
    }
  }

  onLogin() {
    const { username, password } = this.loginData;
    if (username && password) {
      this.apiService.post('login', this.loginData).subscribe(
        response => {
          const token = response.token;

          // token will only be given if the login was successful
          if (token) {
            // store JWT Token in the short-term session storage
            sessionStorage.setItem('token', token);
            console.log('Login successful - moving to home', response);
            // redirect to the home page
            this.router.navigate(['/home']);
          } else {
            console.error("Unsuccessful login");
          }
        },
        error => {
          // 401 status handling was helped generated by ChatGPT
          if (error.status === 401) {
            console.error('Login failed: Invalid username or password.');
          } else {
            console.error('Login failed', error);
          }
        }
      );
    } else {
      console.error('Please provide both username and password.');
    }
  }
}
