package edu.carroll.doin_backend.repo;

import java.util.List;

import edu.carroll.doin_backend.web.model.User;
import org.springframework.data.jpa.repository.JpaRepository;


public interface LoginRepository extends JpaRepository<User, Integer> {
  /**
   * Finds a list of users by their username, ignoring case.
   * <p>
   * This method is autogenerated by Spring, but it will find all users with the username 
   * that matches the username parameter entered into the method. Assuming usernames have 
   * to be unique, the list should be only 1 User long.
   * </p>
   *
   * @param username the username to search for, case-insensitive.
   * @return a list of {@link User} objects that match the given username, ignoring case.
   */
  List<User> findbyUsernameIgnoreCase(String username);
}
